# Generated by Django 6.0.5 on 2026-05-12 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementCategories',
            fields=[
                ('acid', models.AutoField(db_column='ACid', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'AnnouncementCategories',
            },
        ),
        migrations.CreateModel(
            name='ComplaintType',
            fields=[
                ('ctid', models.AutoField(db_column='CTID', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=100, null=True)),
            ],
            options={
                'db_table': 'ComplaintType',
            },
        ),
        migrations.CreateModel(
            name='DocumentTypes',
            fields=[
                ('dtid', models.AutoField(db_column='DTID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DocumentTypes',
            },
        ),
        migrations.CreateModel(
            name='HearingLevel',
            fields=[
                ('hearinglevelid', models.AutoField(db_column='HearingLevelID', primary_key=True, serialize=False)),
                ('level_type', models.CharField(blank=True, db_column='Level_Type', max_length=100, null=True)),
            ],
            options={
                'db_table': 'HearingLevel',
            },
        ),
        migrations.CreateModel(
            name='HearingStatus',
            fields=[
                ('statusid', models.AutoField(db_column='StatusID', primary_key=True, serialize=False)),
                ('statustype', models.CharField(blank=True, db_column='StatusType', max_length=100, null=True)),
            ],
            options={
                'db_table': 'HearingStatus',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('permissionid', models.AutoField(db_column='PermissionID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('positionid', models.AutoField(db_column='PositionID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roleid', models.AutoField(db_column='RoleID', primary_key=True, serialize=False)),
                ('rolename', models.CharField(blank=True, db_column='RoleName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='SLAModules',
            fields=[
                ('moduleid', models.AutoField(db_column='ModuleID', primary_key=True, serialize=False)),
                ('module_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'SLAModules',
            },
        ),
        migrations.CreateModel(
            name='TypeOfID',
            fields=[
                ('toid', models.AutoField(db_column='ToID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'TypeOfID',
            },
        ),
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('usertypeid', models.AutoField(db_column='UserTypeID', primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'UserTypes',
            },
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('complaintsid', models.AutoField(db_column='ComplaintsID', primary_key=True, serialize=False)),
                ('complainee', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('file', models.BinaryField(blank=True, db_column='File', null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('dateadded', models.DateTimeField(auto_now_add=True, db_column='DateAdded')),
                ('datefinish', models.DateTimeField(blank=True, db_column='DateFinish', null=True)),
                ('complaint_type', models.ForeignKey(blank=True, db_column='complaint_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.complainttype')),
            ],
            options={
                'db_table': 'Complaints',
            },
        ),
        migrations.CreateModel(
            name='DocumentFields',
            fields=[
                ('dfid', models.AutoField(db_column='DFID', primary_key=True, serialize=False)),
                ('field_label', models.CharField(blank=True, max_length=100, null=True)),
                ('field_type', models.CharField(blank=True, max_length=20, null=True)),
                ('is_required', models.BooleanField(blank=True, null=True)),
                ('document_type', models.ForeignKey(blank=True, db_column='document_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.documenttypes')),
            ],
            options={
                'db_table': 'DocumentFields',
            },
        ),
        migrations.CreateModel(
            name='ComplaintHearing',
            fields=[
                ('chid', models.AutoField(db_column='CHID', primary_key=True, serialize=False)),
                ('hearing_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('complaint', models.ForeignKey(db_column='complaint_id', on_delete=django.db.models.deletion.CASCADE, to='core.complaints')),
                ('hearing_level', models.ForeignKey(db_column='hearing_level_id', on_delete=django.db.models.deletion.CASCADE, to='core.hearinglevel')),
                ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, to='core.hearingstatus')),
            ],
            options={
                'db_table': 'ComplaintHearing',
            },
        ),
        migrations.CreateModel(
            name='SLATracking',
            fields=[
                ('slaid', models.AutoField(db_column='SLAID', primary_key=True, serialize=False)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('priority_level', models.CharField(blank=True, max_length=20, null=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('sla_status', models.CharField(blank=True, max_length=20, null=True)),
                ('response_time_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(blank=True, db_column='module_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.slamodules')),
            ],
            options={
                'db_table': 'SLATracking',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=50, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('firstname', models.CharField(blank=True, db_column='Firstname', max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, db_column='Lastname', max_length=100, null=True)),
                ('middlename', models.CharField(blank=True, db_column='Middlename', max_length=100, null=True)),
                ('contactno', models.CharField(blank=True, db_column='ContactNo', max_length=20, null=True, unique=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=10, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_first_login', models.BooleanField(default=True)),
                ('is_password_changed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(blank=True, db_column='position_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.positions')),
                ('role', models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.roles')),
                ('user_type', models.ForeignKey(db_column='user_type_id', on_delete=django.db.models.deletion.CASCADE, to='core.usertypes')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='SMSSubscriptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'db_table': 'SMSSubscriptions',
            },
        ),
        migrations.CreateModel(
            name='SMSOutbox',
            fields=[
                ('outboxid', models.AutoField(db_column='OutboxID', primary_key=True, serialize=False)),
                ('recipient_number', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_by', models.ForeignKey(blank=True, db_column='sent_by', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'db_table': 'SMS_Outbox',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('settingsid', models.AutoField(db_column='SettingsID', primary_key=True, serialize=False)),
                ('notifications_enabled', models.BooleanField(blank=True, null=True)),
                ('dark_mode', models.BooleanField(blank=True, null=True)),
                ('text_size', models.CharField(blank=True, max_length=10, null=True)),
                ('receive_sms', models.BooleanField(blank=True, db_column='receive_SMS', null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'db_table': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='ResidentVerification',
            fields=[
                ('rv_id', models.AutoField(db_column='RV_ID', primary_key=True, serialize=False)),
                ('id_image', models.BinaryField(blank=True, null=True)),
                ('selfie_image', models.BinaryField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('toid', models.ForeignKey(blank=True, db_column='ToID', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.typeofid')),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident_verifications_reviewed', to='core.users')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'db_table': 'ResidentVerification',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('otpid', models.AutoField(db_column='OtpID', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=10, null=True)),
                ('purpose', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'db_table': 'OTP',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('cuid', models.AutoField(db_column='CUID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='Firstname', max_length=250)),
                ('lastname', models.CharField(db_column='Lastname', max_length=250)),
                ('contactno', models.CharField(db_column='ContactNo', max_length=20)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('messagesubject', models.CharField(blank=True, db_column='MessageSubject', max_length=255, null=True)),
                ('message', models.TextField(blank=True, db_column='Message', null=True)),
                ('status', models.CharField(db_column='Status', default='New', max_length=20)),
                ('admin_reply', models.TextField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('replied_byuser', models.ForeignKey(blank=True, db_column='replied_byUser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries_replied', to='core.users')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'db_table': 'Inquiry',
            },
        ),
        migrations.CreateModel(
            name='HearingOfficials',
            fields=[
                ('hoid', models.AutoField(db_column='HOID', primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('complaint', models.ForeignKey(db_column='complaint_id', on_delete=django.db.models.deletion.CASCADE, to='core.complaints')),
                ('user_officials', models.ForeignKey(db_column='user_officials_id', on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'db_table': 'HearingOfficials',
            },
        ),
        migrations.CreateModel(
            name='DocumentRequests',
            fields=[
                ('drid', models.AutoField(db_column='DRID', primary_key=True, serialize=False)),
                ('request_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('generated_file', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_file', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.ForeignKey(blank=True, db_column='document_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.documenttypes')),
                ('processed_by', models.ForeignKey(blank=True, db_column='processed_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_requests_processed', to='core.users')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'db_table': 'DocumentRequests',
            },
        ),
        migrations.CreateModel(
            name='ComplaintUpdates',
            fields=[
                ('cuid', models.AutoField(db_column='CUID', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('complaint', models.ForeignKey(blank=True, db_column='complaint_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.complaints')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'db_table': 'ComplaintUpdates',
            },
        ),
        migrations.AddField(
            model_name='complaints',
            name='complainant_user',
            field=models.ForeignKey(blank=True, db_column='complainant_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.users'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='handled_by',
            field=models.ForeignKey(blank=True, db_column='handled_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_handled', to='core.users'),
        ),
        migrations.CreateModel(
            name='AuditLogs',
            fields=[
                ('logid', models.AutoField(db_column='LogID', primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('module_name', models.CharField(blank=True, max_length=50, null=True)),
                ('table_name', models.CharField(blank=True, max_length=100, null=True)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'db_table': 'AuditLogs',
            },
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('announcement_id', models.AutoField(db_column='Announcement_id', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.BinaryField(blank=True, db_column='File', null=True)),
                ('send_sms', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.announcementcategories')),
                ('posted_by', models.ForeignKey(blank=True, db_column='posted_by', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'db_table': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(db_column='PermissionID', on_delete=django.db.models.deletion.CASCADE, to='core.permissions')),
                ('role', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.CASCADE, to='core.roles')),
            ],
            options={
                'db_table': 'RolePermissions',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='AnnouncementFeedback',
            fields=[
                ('afid', models.AutoField(db_column='AFID', primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('announcement', models.ForeignKey(db_column='announcement_id', on_delete=django.db.models.deletion.CASCADE, to='core.announcements')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
            options={
                'db_table': 'AnnouncementFeedback',
                'unique_together': {('announcement', 'user')},
            },
        ),
    ]
