# Generated by Django 6.0.5 on 2026-05-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsoutbox',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smsoutbox',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smsoutbox',
            name='gateway_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smsoutbox',
            name='module_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smsoutbox',
            name='related_record_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smsoutbox',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smsoutbox',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
