# Generated by Django 6.0.5 on 2026-05-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_smsoutbox_created_at_smsoutbox_error_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSModules',
            fields=[
                ('smsmoduleid', models.AutoField(db_column='SMSModuleID', primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SMSModules',
            },
        ),
        migrations.AddField(
            model_name='announcements',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='residentverification',
            name='id_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='residentverification',
            name='selfie_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slatracking',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slatracking',
            name='resolution_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slatracking',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DocumentRequestFieldValues',
            fields=[
                ('drfvid', models.AutoField(db_column='DRFVID', primary_key=True, serialize=False)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('document_field', models.ForeignKey(db_column='document_field_id', on_delete=django.db.models.deletion.CASCADE, to='core.documentfields')),
                ('document_request', models.ForeignKey(db_column='document_request_id', on_delete=django.db.models.deletion.CASCADE, to='core.documentrequests')),
            ],
            options={
                'db_table': 'DocumentRequestFieldValues',
            },
        ),
    ]
