# Generated by Django 6.0.5 on 2026-05-19 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_smsmodules_announcements_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='users',
            name='sex',
        ),
        migrations.AlterField(
            model_name='users',
            name='contactno',
            field=models.CharField(db_column='ContactNo', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='firstname',
            field=models.CharField(db_column='Firstname', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_first_login',
            field=models.BooleanField(db_column='is_first_login', default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_password_changed',
            field=models.BooleanField(db_column='is_password_changed', default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_verified',
            field=models.BooleanField(db_column='is_verified', default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastname',
            field=models.CharField(db_column='Lastname', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='position',
            field=models.ForeignKey(db_column='position_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.positions'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.ForeignKey(db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.roles'),
        ),
    ]
