# Generated by Django 6.0.5 on 2026-06-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_otp_attempts_otp_locked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(blank=True, db_column='Email', max_length=255, null=True, unique=True),
        ),
    ]
