# Generated by Django 6.0.5 on 2026-06-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentverification',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
