# Generated by Django 6.0.5 on 2026-06-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_residentverification_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='complainee_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
