# Generated by Django 6.0.5 on 2026-06-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_complaints_complainee_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
