# Generated by Django 6.0.5 on 2026-06-17 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_announcements_flagged_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategories',
            fields=[
                ('faq_category_id', models.AutoField(db_column='FAQCategoryID', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='CategoryName', max_length=100)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'FAQCategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('faq_id', models.AutoField(db_column='FAQID', primary_key=True, serialize=False)),
                ('question', models.CharField(db_column='Question', max_length=255)),
                ('answer', models.TextField(db_column='Answer')),
                ('created_at', models.DateTimeField(db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(db_column='UpdatedAt')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
            ],
            options={
                'db_table': 'FAQs',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='complainthearing',
            name='outcome',
            field=models.CharField(blank=True, choices=[('Settled', 'Settled'), ('Not Settled', 'Not Settled'), ('No Show', 'No Show'), ('Rescheduled', 'Rescheduled')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complainthearing',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='case_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='external_resolution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='external_resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='external_resolution_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='jurisdiction_barangay',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='non_cooperative_flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='non_cooperative_party',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='settlement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='settlement_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Referred to Proper Barangay', 'Referred to Proper Barangay'), ('Recorded', 'Recorded'), ('Mediation Scheduled', 'Mediation Scheduled'), ('Mediation Ongoing', 'Mediation Ongoing'), ('Settled', 'Settled'), ('For 1st Hearing', 'For 1st Hearing'), ('For 2nd Hearing', 'For 2nd Hearing'), ('For 3rd Hearing', 'For 3rd Hearing'), ('Non-Cooperative Party', 'Non-Cooperative Party'), ('Eligible for Certificate to File Action', 'Eligible for Certificate to File Action'), ('Certificate Issued', 'Certificate Issued'), ('Resolved Outside Barangay', 'Resolved Outside Barangay'), ('Settled in Court', 'Settled in Court'), ('Under Review', 'Under Review'), ('Resolved', 'Resolved'), ('Dismissed', 'Dismissed')], default='Submitted', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CertificateToFileAction',
            fields=[
                ('cfaid', models.AutoField(db_column='CFAID', primary_key=True, serialize=False)),
                ('certificate_no', models.CharField(max_length=50, unique=True)),
                ('issued_at', models.DateTimeField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('complaint', models.OneToOneField(db_column='complaint_id', on_delete=django.db.models.deletion.CASCADE, to='core.complaints')),
                ('issued_by', models.ForeignKey(blank=True, db_column='issued_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.users')),
            ],
            options={
                'db_table': 'CertificateToFileAction',
            },
        ),
        migrations.CreateModel(
            name='HearingAttendance',
            fields=[
                ('attendanceid', models.AutoField(db_column='AttendanceID', primary_key=True, serialize=False)),
                ('participant_type', models.CharField(choices=[('Complainant', 'Complainant'), ('Respondent', 'Respondent')], max_length=20)),
                ('attendance_status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Excused', 'Excused'), ('Refused', 'Refused')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('hearing', models.ForeignKey(db_column='hearing_id', on_delete=django.db.models.deletion.CASCADE, to='core.complainthearing')),
            ],
            options={
                'db_table': 'HearingAttendance',
            },
        ),
    ]
