# Generated by Django 6.0.5 on 2026-06-17 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sync_complaints_full_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarOptions',
            fields=[
                ('avatarid', models.AutoField(db_column='AvatarID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'AvatarOptions',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ForeignKey(blank=True, db_column='avatar_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.avataroptions'),
        ),
    ]
