# Generated by Django 6.0.5 on 2026-06-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_avataroptions_users_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='external_resolution_status',
        ),
    ]
