# Generated by Django 6.0.5 on 2026-06-17 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_complaints_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrequests',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='documentrequestfieldvalues',
            name='uploaded_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentrequestfieldvalues',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
