# Generated by Django 6.0.5 on 2026-06-17 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_documentrequests_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='complaint_type',
            field=models.ForeignKey(blank=True, db_column='complaint_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='core.complainttype'),
        ),
    ]
