# Generated by Django 6.0.5 on 2026-06-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_complaints_complaint_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('For Chairman Review', 'For Chairman Review'), ('Referred to Proper Barangay', 'Referred to Proper Barangay'), ('Ongoing', 'Ongoing'), ('Mediation Scheduled', 'Mediation Scheduled'), ('Mediation Ongoing', 'Mediation Ongoing'), ('Settled', 'Settled'), ('For 1st Hearing', 'For 1st Hearing'), ('For 2nd Hearing', 'For 2nd Hearing'), ('For 3rd Hearing', 'For 3rd Hearing'), ('Non-Cooperative Party', 'Non-Cooperative Party'), ('Eligible for Certificate to File Action', 'Eligible for Certificate to File Action'), ('Certificate Issued', 'Certificate Issued'), ('Resolved Outside Barangay', 'Resolved Outside Barangay'), ('Settled in Court', 'Settled in Court'), ('Under Review', 'Under Review'), ('Resolved', 'Resolved'), ('Dismissed', 'Dismissed')], default='Submitted', max_length=50, null=True),
        ),
    ]
