# Generated by Django 6.0.5 on 2026-06-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_complaints_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(blank=True, db_column='Address', max_length=255, null=True),
        ),
    ]
