# Generated by Django 6.0.5 on 2026-06-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_users_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequests',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
