# Generated by Django 6.0.5 on 2026-06-24 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_documentrequests_admin_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='faq_category',
            field=models.ForeignKey(blank=True, db_column='FAQCategoryID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faqcategories'),
        ),
    ]
