# Generated by Django 6.0.5 on 2026-06-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_inquiry_faq_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
