# Generated by Django 6.0.5 on 2026-06-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_complaints_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='incident_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
