# Generated by Django 6.0.5 on 2026-06-29 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_complaints_incident_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsoutbox',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
