# Generated by Django 6.0.5 on 2026-07-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_smsoutbox_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSModules',
        ),
        migrations.RemoveField(
            model_name='smsoutbox',
            name='module_id',
        ),
    ]
