# Generated by Django 6.0.6 on 2026-07-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_delete_smsmodules_remove_smsoutbox_module_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
    ]
