# Generated by Django 6.0.6 on 2026-07-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_positions_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_we_do_en', models.TextField()),
                ('what_we_do_tl', models.TextField()),
                ('mission_en', models.TextField()),
                ('mission_tl', models.TextField()),
                ('vision_en', models.TextField()),
                ('vision_tl', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
