# Generated by Django 6.0.6 on 2026-07-23 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_aboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
