# Generated by Django 6.0.6 on 2026-07-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_delete_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('what_we_do', 'What we do'), ('mission', 'Mission'), ('vision', 'Vision')], max_length=20)),
                ('content_en', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
