# Generated by Django 6.0.6 on 2026-07-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_aboutusstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttypes',
            name='processing_time',
            field=models.CharField(default='1-2 days', max_length=50),
        ),
    ]
