# Generated by Django 6.0.6 on 2026-07-23 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_documenttypes_processing_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUsStatement',
        ),
    ]
