# Generated by Django 6.0.6 on 2026-07-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_delete_aboutusstatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('what_we_do', 'What We Do'), ('mission', 'Our Mission'), ('vision', 'Our Vision')], max_length=20, unique=True)),
                ('content_en', models.TextField(max_length=800)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
